version: "3"

services:
  web:
    build: .
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-net

  certbot:
    image: certbot/certbot
    volumes:
      - ./html:/usr/share/nginx/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait ${!}; done;'"

networks:
  nginx-net:

volumes:
  certbot-etc:
  certbot-var:
